services:
  - type: web
    name: pronto-backend
    env: node
    plan: free
    buildCommand: npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
